/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class logger_Record */

#ifndef _Included_logger_Record
#define _Included_logger_Record
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     logger_Record
 * Method:    addPutFieldRecord
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_logger_Record_addPutFieldRecord
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

/*
 * Class:     logger_Record
 * Method:    addNewRecord
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_logger_Record_addNewRecord
  (JNIEnv *, jclass, jlong, jint, jint, jint, jlong);

JNIEXPORT void JNICALL Java_logger_Record_addConstructRecord
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     logger_Record
 * Method:    addAASTORERecord
 * Signature: (JIJII)V
 */
JNIEXPORT void JNICALL Java_logger_Record_addAASTORERecord
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint);

JNIEXPORT jlong JNICALL Java_logger_Record_getTid
  (JNIEnv *jvmti_env, jclass klass);

JNIEXPORT jlong JNICALL Java_logger_Record_getPid
  (JNIEnv *jvmti_env, jclass klass);

JNIEXPORT void JNICALL Java_logger_Record_addUseRecord
  (JNIEnv *, jclass, jint, jlong, jint, jint);

JNIEXPORT void JNICALL Java_logger_Record_addFreeRecord
  (JNIEnv *, jclass, jlong, jlong);
JNIEXPORT void JNICALL Java_logger_Record_doSomething
  (JNIEnv *, jclass, jlong);

// 3th- : ref, value, line, classid, fieldid, is_put
JNIEXPORT void JNICALL Java_logger_Record_addFieldValueRecordJint
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_logger_Record_addFieldValueRecordJlong
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_logger_Record_addFieldValueRecordJfloat
  (JNIEnv *, jclass, jlong, jfloat, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_logger_Record_addFieldValueRecordJdouble
  (JNIEnv *, jclass, jlong, jdouble, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_logger_Record_addFieldValueRecordJstring
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jboolean);

JNIEXPORT void JNICALL Java_logger_Record_addStaticFieldValueRecordJint
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_logger_Record_addStaticFieldValueRecordJlong
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_logger_Record_addStaticFieldValueRecordJfloat
  (JNIEnv *, jclass, jfloat, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_logger_Record_addStaticFieldValueRecordJdouble
  (JNIEnv *, jclass, jdouble, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_logger_Record_addStaticFieldValueRecordJstring
  (JNIEnv *, jclass, jstring, jint, jint, jint, jboolean);
JNIEXPORT jboolean JNICALL Java_logger_Record_addContainerRecordList5
  (JNIEnv *jvmti_env, jclass klass, jboolean retobj, jobject holder, jobject ref, jint size, jint cid, jint copid);
JNIEXPORT void JNICALL Java_logger_Record_addContainerRecordList6
  (JNIEnv *jvmti_env, jclass klass, jobject holder, jint idx, jobject ref, jint size, jint cid, jint copid);
JNIEXPORT void JNICALL Java_logger_Record_addContainerRecordList4
  (JNIEnv *jvmti_env, jclass klass, jobject holder, jint size, jint cid, jint copid);
JNIEXPORT void JNICALL Java_logger_Record_addContainerRecordMap4
  (JNIEnv *jvmti_env, jclass klass, jobject holder, jint size, jint cid, jint copid);
JNIEXPORT jint JNICALL Java_logger_Record_addContainerRecordListI5
  (JNIEnv *jvmti_env, jclass klass, jint idx, jobject holder, jobject ref, jint size, jint cid, jint copid);
JNIEXPORT jobject JNICALL Java_logger_Record_addContainerRecordList15
  (JNIEnv *jvmti_env, jclass klass, jobject retobj, jobject holder, jint idx_or_succ, jint size, jint cid, jint copid);
JNIEXPORT jobject JNICALL Java_logger_Record_addContainerRecordList14
  (JNIEnv *jvmti_env, jclass klass, jobject retobj, jobject holder, jint size, jint cid, jint copid);
JNIEXPORT jobject JNICALL Java_logger_Record_addContainerRecordMap15
  (JNIEnv *jvmti_env, jclass klass, jobject retobj, jobject holder, jobject key, jint size, jint cid, jint copid);
JNIEXPORT void JNICALL Java_logger_Record_addContainerRecordMap5
  (JNIEnv *jvmti_env, jclass klass, jobject holder, jobject map, jint size, jint cid, jint copid);
JNIEXPORT jobject JNICALL Java_logger_Record_addContainerRecordMap16
  (JNIEnv *jvmti_env, jclass klass, jobject retobj, jobject holder, jobject key, jobject value, jint size, jint cid, jint copid);
JNIEXPORT void JNICALL Java_logger_Record_decreaseContainerFilterFlag
  (JNIEnv *jvmti_env, jclass klass);
JNIEXPORT void JNICALL Java_logger_Record_unsetIsRightAfter
  (JNIEnv *jvmti_env, jclass klass);
JNIEXPORT void JNICALL Java_logger_Record_enableRecord
  (JNIEnv *jvmti_env, jclass klass);
JNIEXPORT void JNICALL Java_logger_Record_disableRecord
  (JNIEnv *jvmti_env, jclass klass);
JNIEXPORT void JNICALL Java_logger_Record_enablePrintNew
  (JNIEnv *jvmti_env, jclass klass);
JNIEXPORT void JNICALL Java_logger_Record_disablePrintNew
  (JNIEnv *jvmti_env, jclass klass);
JNIEXPORT jboolean JNICALL Java_logger_Record_getPrintNew
  (JNIEnv *jvmti_env, jclass klass);
JNIEXPORT void JNICALL Java_logger_Record_addContainerLineInfoRecord
  (JNIEnv *, jclass, jint line, jint class_name_id);
  // (JNIEnv *, jclass, jobject holder, jint line, jint class_name_id);
JNIEXPORT void JNICALL Java_logger_Record_printCallTrace
  (JNIEnv *, jclass);
JNIEXPORT jlong JNICALL Java_logger_Record_allocateArgsBuffer
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_logger_Record_printArgs
  (JNIEnv *, jclass, jint pos, jint type);
JNIEXPORT void JNICALL Java_logger_Record_putInt
  (JNIEnv *, jclass, jlong pos, jint val);
JNIEXPORT void JNICALL Java_logger_Record_putLong
  (JNIEnv *, jclass, jlong pos, jlong val);
JNIEXPORT void JNICALL Java_logger_Record_putDouble
  (JNIEnv *, jclass, jlong pos, jdouble val);
JNIEXPORT void JNICALL Java_logger_Record_putFloat
  (JNIEnv *, jclass, jlong pos, jfloat val);

JNIEXPORT void JNICALL Java_logger_Record_addTagNewRecord
  (JNIEnv *jni_env, jclass klass, jobject obj, jint obj_typeid, jint line, jint class_name_id, jlong obj_size);

JNIEXPORT void JNICALL Java_logger_Record_addTagPutFieldRecord
  (JNIEnv *jni_env, jclass klass, jobject holder, jobject ref, jint line, jint class_name_id, int field_id);

JNIEXPORT void JNICALL Java_logger_Record_addTagConstructRecord
  (JNIEnv *jni_env, jclass klass, jobject obj, jint obj_typeid, jint line, jint class_name_id);

JNIEXPORT void JNICALL Java_logger_Record_addTagAASTORERecord
  (JNIEnv *jni_env, jclass klass, jobject holder, jint index, jobject ref, jint line, jint class_name_id);

JNIEXPORT void JNICALL Java_logger_Record_addTagUseRecord
  (JNIEnv *jni_env, jclass klass, jint type, jobject obj, jint line, jint class_name_id );

// #define Java_logger_Record_addFieldValueRecord(type,jvmti_env, klass, addr, value, line, class_name_id, field_id, is_put) JNIEXPORT void JNICALL Java_logger_Record_addFieldValueRecord_##type \
//   (jvmti_env, klass, addr, value, line, class_name_id, field_id, is_put);

// Java_logger_Record_addFieldValueRecord(jint,JNIEnv *, jclass, jlong, jint, jint, jint, jint, jboolean)
// Java_logger_Record_addFieldValueRecord(jlong,JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jboolean)
// Java_logger_Record_addFieldValueRecord(jfloat,JNIEnv *, jclass, jlong, jfloat, jint, jint, jint, jboolean)
// Java_logger_Record_addFieldValueRecord(jdouble,JNIEnv *, jclass, jlong, jdouble, jint, jint, jint, jboolean)
#ifdef __cplusplus
}
#endif
#endif
